### ISSUE TITLE
Repo stars always show as zero

### ISSUE THREAD

**Issue by jamesmunns** [pbzweihander/rust-trending#2]
For the last day or so (since 2019-10-26), all repositories are show with zero stars, even when they have significantly more.

Perhaps the Github API changed somehow?

**Comment by pbzweihander** [comment]
It seems like there is some problems in github trending api (https://github.com/huchenme/github-trending-api). The response has 0 stars for all repository.

**Comment by pbzweihander** [comment]
Resolved by https://github.com/huchenme/github-trending-api/pull/74
